### ISSUE TITLE
Upcoming Events section

### ISSUE THREAD

**Issue by acmjec** [acmjec/Hacktoberfest2023-Web-Development#2]
Refer to the Figma design and create a fully responsive 'upcoming events' section.
Check the attached screenshot for reference:

![image](https://github.com/acmjec/Hacktoberfest2023-Web-Development/assets/91929636/d4d6a9f5-d000-4334-8698-d4606838fed1)

**Comment by A-R-P-I-T-JAIN** [comment]
assign it to me

**Comment by A-R-P-I-T-JAIN** [comment]
submitted my PR
