### ISSUE TITLE
Create the Events section

### ISSUE THREAD

**Issue by acmjec** [acmjec/Hacktoberfest2023-Web-Development#3]
![image](https://github.com/acmjec/Hacktoberfest2023-Web-Development/assets/91929636/e4bf5a96-d753-46f8-ab7c-8179abc74a9a)

Create this section. Refer the Figma design for more details.

**Comment by A-R-P-I-T-JAIN** [comment]
Assign it to me

**Comment by A-R-P-I-T-JAIN** [comment]
Already created this section, will submit my PR soon.

**Comment by A-R-P-I-T-JAIN** [comment]
submitted my PR

**Comment by atharv-av** [comment]
It has been merged. Thanks for the contribution.
