### ISSUE TITLE
Explore by category section

### ISSUE THREAD

**Issue by acmjec** [acmjec/Hacktoberfest2023-Web-Development#5]
Create the category section and make sure to make it responsive for all screens.

**Comment by BhaveshDiwale** [comment]
Please assign this issue to me.

**Comment by atharv-av** [comment]
> Please assign this issue to me.

Assigned!

**Comment by AkshatSinghThakur** [comment]
@atharv-av sir I already created this section when you assigned it to me earlier, please check the PR

**Comment by atharv-av** [comment]
> @atharv-av sir I already created this section when you assigned it to me earlier, please check the PR

I just reviewed your PR. It has some issues which I have mentioned there.
